# ~/.config/starship.toml

format = """[â•­â”€â–º](muted_blue)[â®](bold green) $directory[â¯](bold green) $fill $all[â•°â”€â–º](muted_blue)$character"""
#right_format = """$all"""

# Set 'custom' as custom color palette with muted_blue
palette = 'custom'
[palettes.custom]
muted_blue = '#333b52'

[character]
success_symbol = '[â¯](bold green)'
error_symbol = '[â¯](bold red)'

[fill]
symbol = 'â”€'
style = 'bold muted_blue'

[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 30
truncation_symbol = ''
ignore_branches = ['master', 'main']

[line_break]
disabled = false

# NOTE: $gcloud default symbol generates a newline on WSL
[gcloud]
disabled = true
symbol = ''

